-- Team 6 - Hyo Lee, Jennifer Dunham, Daniel Cadwell, Francisco Gutierrez
-- TEAM KICK ASCII

-- CREATE TABLES SCRIPT

ALTER TABLE STORE DROP CONSTRAINT STORE_STORE_MGR_ID_FK;

DROP TABLE LINE;
DROP TABLE PRODUCT;
DROP TABLE INVOICE;
DROP TABLE STORE_CONTACT;
DROP TABLE STORE;
DROP TABLE SALES_REP;
DROP TABLE VENDOR;
DROP TABLE CATEGORY;


CREATE TABLE SALES_REP (
    SLS_REP_ID          NUMBER(10)
        CONSTRAINT SALES_REP_SLS_REP_ID_PK PRIMARY KEY,
    SLS_REP_FNAME       VARCHAR2(35)
        CONSTRAINT SALES_REP_SLS_REP_FNAME_NN NOT NULL,
    SLS_REP_LNAME       VARCHAR2(35)
        CONSTRAINT SALES_REP_SLS_REP_LNAME_NN NOT NULL,
    SLS_REP_INITIAL     CHAR(1),
    SLS_REP_EMAIL       VARCHAR2(30),
    SLS_REP_PHONE       VARCHAR2(15)
        CONSTRAINT SALES_REP_SLS_REP_PHONE_NN NOT NULL
);


CREATE TABLE STORE (
    STORE_NUM           NUMBER(10)
        CONSTRAINT STORE_STORE_NUM_PK PRIMARY KEY,
    STORE_NAME          VARCHAR2(40)
        CONSTRAINT STORE_STORE_NAME_NN NOT NULL,
    STORE_ADDRESS       VARCHAR2(80)
        CONSTRAINT STORE_STORE_ADDRESS_NN NOT NULL,
    STORE_CITY          VARCHAR2(40)
        CONSTRAINT STORE_STORE_CITY_NN NOT NULL,
    STORE_STATE         CHAR(2)
        CONSTRAINT STORE_STORE_STATE_NN NOT NULL,
    STORE_ZIP           VARCHAR2(10)
        CONSTRAINT STORE_STORE_ZIP_NN NOT NULL,
    STORE_PHONE         VARCHAR2(15)
        CONSTRAINT STORE_STORE_PHONE_NN NOT NULL,
    MGR_ID              NUMBER(10)
);


CREATE TABLE STORE_CONTACT (
    CONTACT_ID          NUMBER(10)
        CONSTRAINT STORE_CONTACT_CONTACT_ID_PK PRIMARY KEY,
    STORE_NUM           NUMBER(10),
    CONTACT_FNAME       VARCHAR2(35)
        CONSTRAINT STORE_CONTACT_CONTACT_FNAME_NN NOT NULL,
    CONTACT_LNAME       VARCHAR2(35)
        CONSTRAINT STORE_CONTACT_CONTACT_LNAME_NN NOT NULL,
    CONTACT_INITIAL     CHAR(1),
    CONTACT_EMAIL       VARCHAR2(30),
    CONTACT_PHONE       VARCHAR2(15)
        CONSTRAINT STORE_CONTACT_CONTACT_PHONE_NN NOT NULL,
    CONTACT_JOB_TITLE   VARCHAR2(30),
        CONSTRAINT STORE_CONTACT_STORE_NUM_FK FOREIGN KEY(STORE_NUM) REFERENCES STORE(STORE_NUM)
);

-- ADD CONSTRAINT AFTER STORE_CONTACT TABLE CREATION -
ALTER   TABLE  STORE
ADD     CONSTRAINT STORE_STORE_MGR_ID_FK FOREIGN KEY(MGR_ID) REFERENCES STORE_CONTACT(CONTACT_ID);


CREATE TABLE INVOICE (
    INV_NUM             NUMBER(10)
        CONSTRAINT INVOICE_INV_NUM_PK PRIMARY KEY,
    STORE_NUM           NUMBER(10),
    ORDERED_BY          NUMBER(10),
    SLS_REP_ID          NUMBER(10),
    INV_DATE            DATE
        CONSTRAINT INVOICE_INV_DATE_NN NOT NULL,
    INV_SHIP_DATE        DATE,
        CONSTRAINT INVOICE_STORE_NUM_FK FOREIGN KEY(STORE_NUM) REFERENCES STORE(STORE_NUM),
        CONSTRAINT INVOICE_STORE_CONTACT_FK FOREIGN KEY(ORDERED_BY) REFERENCES STORE_CONTACT(CONTACT_ID),
        CONSTRAINT INVOICE_SLS_REP_ID_FK FOREIGN KEY(SLS_REP_ID) REFERENCES SALES_REP(SLS_REP_ID)
);


CREATE TABLE VENDOR (
    VEND_NUM            NUMBER(10)
        CONSTRAINT VENDOR_VEND_NUM_PK PRIMARY KEY,
    VEND_NAME           VARCHAR2(40)
        CONSTRAINT VENDOR_VEND_NAME_NN NOT NULL,
    VEND_ADDRESS        VARCHAR2(80),
    VEND_CITY           VARCHAR2(40),
    VEND_STATE          CHAR(2),
    VEND_ZIP            VARCHAR2(10),
    VEND_PHONE          VARCHAR2(15)
        CONSTRAINT VENDOR_VEND_PHONE_NN NOT NULL
);


CREATE TABLE CATEGORY (
    CAT_NUM             NUMBER(10)
        CONSTRAINT CATEGORY_CAT_NUM_PK PRIMARY KEY,
    CAT_NAME            VARCHAR2(35)
        CONSTRAINT CATEGORY_CAT_NAME_NN NOT NULL
);


CREATE TABLE PRODUCT (
    PROD_NUM            NUMBER(10)
        CONSTRAINT PRODUCT_PROD_NUM_PK PRIMARY KEY,
    VEND_NUM            NUMBER(10),
    PROD_DESC           VARCHAR2(225),
    PROD_PRICE          NUMBER(6,2),
    PROD_QOH            NUMBER(5),
    CAT_NUM             NUMBER(10),
    REORDER_LEVEL       NUMBER(5),
        CONSTRAINT PRODUCT_VEND_NUM_FK FOREIGN KEY(VEND_NUM) REFERENCES VENDOR(VEND_NUM),
        CONSTRAINT PRODUCT_CAT_NUM_FK FOREIGN KEY(CAT_NUM) REFERENCES CATEGORY(CAT_NUM)
);


CREATE TABLE LINE (
    LINE_NUM            NUMBER(10),
    INV_NUM             NUMBER(10),
    PROD_NUM            NUMBER(10),
    LINE_QTY            NUMBER(4)
        CONSTRAINT LINE_LINE_QTY_NN NOT NULL,
    LINE_PRICE          NUMBER(5,2)
        CONSTRAINT LINE_LINE_PRICE_NN NOT NULL,
        CONSTRAINT LINE_LINE_NUM_INV_NUM_PK PRIMARY KEY(LINE_NUM, INV_NUM),
        CONSTRAINT LINE_INV_NUM_FK  FOREIGN KEY(INV_NUM) REFERENCES INVOICE(INV_NUM),
        CONSTRAINT LINE_PROD_NUM_FK FOREIGN KEY(PROD_NUM) REFERENCES PRODUCT(PROD_NUM),
    LINE_TOTAL          NUMBER(8,2) AS (LINE_QTY*LINE_PRICE)
);

COMMIT;