-- Team 6 - Hyo Lee, Jennifer Dunham, Daniel Cadwell, Francisco Gutierrez
-- TEAM KICK ASCII

-- INSERT DATA SCRIPT

DROP sequence slsRepID;
DROP sequence storeNum;
DROP sequence storeContact;
DROP sequence invNum;
DROP sequence CAT_NUM;
DROP sequence VENDORNum;
DROP sequence prodNum;


CREATE sequence slsRepID
MINVALUE 1
START WITH 1
INCREMENT by 1
CACHE 5;

INSERT INTO SALES_REP VALUES (slsRepID.nextval,'Hyo', 'Lee', NULL, 'hyo@hotmail.com','7145551234');
INSERT INTO SALES_REP VALUES (slsRepID.nextval,'Jennifer', 'Dunham', 'A', 'jedunham@csumb.edu','6265554321');
INSERT INTO SALES_REP VALUES (slsRepID.nextval,'Francisco', 'Gutierrez', 'E', 'fgutierrez@gmail.com','6056974855');
INSERT INTO SALES_REP VALUES (slsRepID.nextval,'Daniel', 'Cadwell', 'T', NULL,'2136592365');
INSERT INTO SALES_REP VALUES (slsRepID.nextval,'Wendy', 'Wang', 'H', 'howang@csumb.edu', '3132589651');


CREATE sequence storeNum
MINVALUE 1
START WITH 1
INCREMENT by 1
CACHE 5;

INSERT INTO STORE VALUES (storeNum.nextval, 'Barkeley Sports', '555 Main St', 'Irwindale', 'CA', '91706', '8885557890', NULL);
INSERT INTO STORE VALUES (storeNum.nextval, 'Supreme Competition', '777 Ayerdale Dr', 'San Diego', 'CA', '92104', '7205557890', NULL);
INSERT INTO STORE VALUES (storeNum.nextval, 'Sun and Snow, Inc.', '98028 E St', 'Florence', 'SC', '29503', '5145552222', NULL);
INSERT INTO STORE VALUES (storeNum.nextval, 'Myers Apparel', '790 McCallister Cir', 'Henderson', 'NV', '89122', '3905551345', NULL);
INSERT INTO STORE VALUES (storeNum.nextval, 'Barkeley Sports', '1234 Stratford Ave', 'Jersey City', 'NJ', '07097', '7605551432', NULL);
INSERT INTO STORE VALUES (storeNum.nextval, 'Sticks and Balls', '14445 Sesame St', 'New York', 'NY', '10001', '6365558972', NULL);
INSERT INTO STORE VALUES (storeNum.nextval, 'Arena Supply', '87 Arena Dr', 'Chicago', 'IL', '60604', '4305558901', NULL);
INSERT INTO STORE VALUES (storeNum.nextval, 'Stadium Gear', '876 Miami Rd', 'Boston', 'MA', '02108', '2305557891', NULL);
INSERT INTO STORE VALUES (storeNum.nextval, 'Sun and Snow, Inc.', '88 Rolling Hills Rd', 'Diamond Bar', 'CA', '91765', '9095558711', NULL);
INSERT INTO STORE VALUES (storeNum.nextval, 'Extreme Supplies', '888 Percy Rd', 'Sunnyvale', 'CA', '95002', '7815557189', NULL);


CREATE sequence storeContact
MINVALUE 1
START WITH 1
INCREMENT by 1
CACHE 5;

INSERT INTO STORE_CONTACT VALUES (storeContact.nextval, 1, 'Frank', 'Azarea', 'L', 'fazarea@email.com', '8885557256', 'Purchasing Mgr');
INSERT INTO STORE_CONTACT VALUES (storeContact.nextval, 1, 'Judy', 'Welch', NULL, 'jwelch@email.com', '8885557209', 'Store Mgr');
INSERT INTO STORE_CONTACT VALUES (storeContact.nextval, 2, 'Satish', 'Karnik', 'A', 'skarnik@email.com', '7205557810', 'Store Mgr');
INSERT INTO STORE_CONTACT VALUES (storeContact.nextval, 3, 'Abimbola', 'Chahine', NULL, 'achahine@email.com', '5145557000', 'Store Mgr');
INSERT INTO STORE_CONTACT VALUES (storeContact.nextval, 4, 'John', 'Marcone', 'A', 'jmarcone@email.com', '3905558706', 'Receptionist');
INSERT INTO STORE_CONTACT VALUES (storeContact.nextval, 4, 'Janet', 'Roulette', 'F', 'jroulette@email.com', '3905554870','Store Mgr');
INSERT INTO STORE_CONTACT VALUES (storeContact.nextval, 5, 'Hiyoko', 'Fujimoto', NULL, 'hfujimoto@email.com', '7605550042', 'Store Mgr');
INSERT INTO STORE_CONTACT VALUES (storeContact.nextval, 6, 'Alice', 'Wonderland', 'N', 'awonderland@email.com', '6365557058', 'Store Mgr');
INSERT INTO STORE_CONTACT VALUES (storeContact.nextval, 7, 'Longjohn', 'Silver', NULL, 'lsilver@email.com', '4305558544', 'Store Mgr');
INSERT INTO STORE_CONTACT VALUES (storeContact.nextval, 8, 'Savita', 'Chande', NULL, 'schande@email.com', '2305556455', 'Store Mgr');
INSERT INTO STORE_CONTACT VALUES (storeContact.nextval, 9, 'Mario', 'Rodriguez', 'C', 'mrodriguez@email.com', '9095555333', 'Store Mgr');
INSERT INTO STORE_CONTACT VALUES (storeContact.nextval, 10, 'Feliciano', 'Lopez', 'L', 'flopez@email.com', '7815559990', 'Store Mgr');
UPDATE STORE SET MGR_ID = 2 WHERE STORE_NUM = 1;
UPDATE STORE SET MGR_ID = 3 WHERE STORE_NUM = 2;
UPDATE STORE SET MGR_ID = 4 WHERE STORE_NUM = 3;
UPDATE STORE SET MGR_ID = 6 WHERE STORE_NUM = 4;
UPDATE STORE SET MGR_ID = 7 WHERE STORE_NUM = 5;
UPDATE STORE SET MGR_ID = 8 WHERE STORE_NUM = 6;
UPDATE STORE SET MGR_ID = 9 WHERE STORE_NUM = 7;
UPDATE STORE SET MGR_ID = 10 WHERE STORE_NUM = 8;
UPDATE STORE SET MGR_ID = 11 WHERE STORE_NUM = 9;
UPDATE STORE SET MGR_ID = 12 WHERE STORE_NUM = 10;


CREATE sequence invNum
MINVALUE 10000
START WITH 10000
INCREMENT by 1
CACHE 5;

INSERT INTO INVOICE VALUES (invNum.nextval, 1, 1, 4, '01-Jan-15', '03-Jan-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 4, 6, 2, '03-Jan-15', '05-Jan-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 10, 12, 5, '02-Feb-15', '04-Feb-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 8, 10, 4, '18-Feb-15', '21-Feb-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 10, 12, 5, '01-Mar-15', '04-Mar-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 1, 2, 1, '01-Mar-15', '03-Mar-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 5, 7, 2, '03-Mar-15', '05-Mar-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 8, 10, 5, '07-Mar-15', '09-Mar-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 8, 10, 1, '09-Mar-15', '11-Mar-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 3, 4, 3, '11-Mar-15', '13-Mar-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 9, 11, 5, '15-Mar-15', '17-Mar-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 10, 12, 5, '17-Mar-15', '19-Mar-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 1, 2, 4, '29-Mar-15', '31-Mar-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 6, 8, 2, '31-Mar-15', '02-Apr-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 6, 8, 5, '01-Apr-15', '03-Apr-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 9, 11, 5, '05-Apr-15', '07-Apr-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 2, 3, 5, '16-Apr-15', '18-Apr-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 9, 11, 1, '18-Apr-15', '20-Apr-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 10, 12, 1, '20-Apr-15', '22-Apr-15');
INSERT INTO INVOICE VALUES (invNum.nextval, 8, 10, 2, '20-Apr-15', '22-Apr-15');


CREATE sequence CAT_NUM
MINVALUE 1
START WITH 1
INCREMENT by 1
CACHE 5;

INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Airsoft');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Auto Racing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Archery');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Baseball');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Basketball');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Backpacking');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Badminton');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Bicycling');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Billards');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'BMX Extreme');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Boating');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Bodybuilding');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'BodySurfing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Bowling');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Boxing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Cave Diving');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Canoeing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Bungee Jumping');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Chess');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Cricket');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Darts');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Diving');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Dog Sledding');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Extreem Sports');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Fantsy Sports');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Fencing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Field Hockey');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Fishing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Football');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Frisbee');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Frog racing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Golf');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Gymnastics');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Handball');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Hang Gliding');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Herding');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Hiking');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Hockey');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Horsing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Hunting');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Hula Hooping');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Hunger Games');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Ice Skating');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Ice Fishing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Speedskating');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Sky Diving');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Jacks');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Judo');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Jump Ropping');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Karate');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Kick Ball');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Kick Boxing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Kite Flying');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Kung Fu');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Lacrosse');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Motocross');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Motorcycle racing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Mountain Biking');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Rowing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Paintball');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Ping Pong');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Pogo Sticking');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Painting');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Pro Wrestling');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Racquetball');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Rafting');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Rodeo');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Roller Derby');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Rope Climbing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Running');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Rugby');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Sailing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Scuba Diving');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Sledding');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Snooker');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Snowboarding');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Snowshoeing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Soccer');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Softball');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Speed Skating');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Tennis');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Tractor Pull');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Volleyball');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Walking');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Water Aerobics');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Water Polo');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Waterskiing');
INSERT INTO CATEGORY VALUES (CAT_NUM.nextval,'Weightlifting');



CREATE sequence VENDORNum
MINVALUE 1
START WITH 1
INCREMENT by 1
CACHE 5;

INSERT INTO VENDOR VALUES (VENDORNum.nextval, 'Kimmel Athletic Manufacturing', '202 E Mission Ave', 'Spokane', 'WA', '99202', '5093267710');
INSERT INTO VENDOR VALUES (VENDORNum.nextval, 'Bear Ice Athletics', '817 Maxwell Ave', 'Evansville', 'IN', '12345', '8124671200');
INSERT INTO VENDOR VALUES (VENDORNum.nextval, 'Okuma, Inc.', '2310 E Locust Court', 'Ontario', 'CA', '91761', '8004665862');
INSERT INTO VENDOR VALUES (VENDORNum.nextval, 'Maurice Sporting Fabrication', '1910 Techny Rd', 'Northbrook', 'IL', '60065', '8477151500');
INSERT INTO VENDOR VALUES (VENDORNum.nextval, 'Sports Masters', '1234 Greenbas Ave', 'Hurley', 'WI', '54534', '8888019164');
INSERT INTO VENDOR VALUES (VENDORNum.nextval, 'Academy Sports', '2121 21st St', 'New York', 'NY', '10001', '6364567890');
INSERT INTO VENDOR VALUES (VENDORNum.nextval, 'Dicks Whips', '21 Mission Dr', 'Chicago', 'IL', '60604', '4305469078');
INSERT INTO VENDOR VALUES (VENDORNum.nextval, 'American Athletics', '1180 Folsom St', 'San Francisco', 'CA', '94103', '4154314931');
INSERT INTO VENDOR VALUES (VENDORNum.nextval, 'Dynasty Footwear', '3415 N Pulaski Rd', 'Chicago', 'IL', '60641', '7732791717');
INSERT INTO VENDOR VALUES (VENDORNum.nextval, 'Vargo Court Masters', '233 N 3rd St', 'Lewisburg', 'PA', '17832', '8059264511');


CREATE sequence prodNum
MINVALUE 1
START WITH 1
INCREMENT by 1
CACHE 5;

INSERT INTO PRODUCT VALUES (prodNum.nextval, 4, 'Tachikara Volleyball', 34.99, 200, 83, 100);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 6, 'Saddle', 97.99, 79, 39, 50);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 2, 'Adamantium Hockey Stick', 529.99, 400, 38, 200);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 7, 'Herding Whip', 34.99, 155, 36, 100);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 3, 'Marble Chess Board', 250.99, 50, 19, 30);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 9, 'Nike Lunar Hyperquickness Shoes (size 12)', 64.99, 700, 5, 400);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 1, 'Shin Guards', 11.99, 180, 78, 150);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 10, 'Shuttlecock (3-pack)', 9.99, 258, 7, 100);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 8, 'Tent (2-person)', 89.99, 132, 6, 100);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 5, 'Labeda Voodoo Derby Roller Skates', 169.99, 260, 68, 100);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 6, 'Mongoose Impasse Dual Full Suspension Bicycle (29-Inch)', 284.99, 42, 8, 25);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 2, 'Candy-Striped Hula Hoop', 13.99, 98, 41, 50);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 4, 'Parachute', 124.99, 132, 46, 100);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 6, 'Back Support Belt', 42.99, 79, 88, 50);
INSERT INTO PRODUCT VALUES (prodNum.nextval, 3, 'Anti Shock Hiking / Walking / Trekking Trail Poles - 1 Pair', 22.99, 105, 37, 100);


INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10000, 3, 30, 529.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (2, 10000, 4, 15, 34.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10001, 2, 10, 97.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10002, 6, 30, 64.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10003, 10, 25, 169.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (2, 10003, 3, 8, 529.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (3, 10003, 5, 7, 250.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10004, 14, 100, 42.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (2, 10004, 6, 80, 64.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10005, 11, 35, 284.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10006, 7, 42, 11.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (2, 10006, 1, 79, 34.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (3, 10006, 3, 125, 529.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (4, 10006, 2, 60, 97.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10007, 7, 20, 11.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10008, 3, 60, 529.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10009, 11, 75, 284.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10010, 2, 90, 97.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10011, 8, 200, 9.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (2, 10011, 1, 150, 34.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10012, 12, 76, 13.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10013, 2, 350, 97.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (2, 10013, 3, 50, 529.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (3, 10013, 6, 225, 64.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10014, 10, 95, 169.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10015, 15, 70, 22.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10016, 3, 30, 529.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (2, 10016, 12, 15, 13.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (3, 10016, 13, 75, 124.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10017, 3, 65, 529.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10018, 8, 100, 9.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (1, 10019, 9, 200, 89.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (2, 10019, 1, 700, 34.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (3, 10019, 15, 600, 22.99);
INSERT INTO LINE (LINE_NUM, INV_NUM, PROD_NUM, LINE_QTY, LINE_PRICE) VALUES (4, 10019, 7, 500, 11.99);


COMMIT;
